--- #YAML:1.0
name: Test-Numeric
version: 0.2
author:
  - Edmund von der Burg <evdb@ecclestoad.co.uk>
  - |-
    Bug reports, patches, suggestions etc are all welcomed.
abstract: Testing utilities for numbers.
license: perl
requires:
  Carp: 0
  Test::Builder: 0
build_requires:
  Module::Build: 0
  Pod::Coverage: 0
  Slurp: 0
  Test::Builder::Tester: 0
  Test::More: 0
  Test::Pod: 0
dynamic_config: 1
provides:
  Test::Numeric:
    file: lib/Test/Numeric.pm
    version: 0.2
generated_by: Module::Build version 0.25
